import type { Asset, TelemetryLog } from '../types';

export const INITIAL_ASSETS: Asset[] = [
  // 10 Gujarat Wind Turbines (Kutch, Saurashtra & Coastal Corridors)
  {
    id: 'TURBINE-001',
    name: 'Kutch Khavda Wind Unit 1',
    type: 'Wind',
    latitude: 23.8512,
    longitude: 69.7541,
    health_score: 98,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Routine scheduled blade inspection in 45 days. Lubrication nominal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-002',
    name: 'Jakhau Coastal Wind Turbine 2',
    type: 'Wind',
    latitude: 23.2340,
    longitude: 68.6920,
    health_score: 95,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Optimal aerodynamic balance. Pitch motors and yaw alignment healthy.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-003',
    name: 'Mahuva Bay Wind Generator 3',
    type: 'Wind',
    latitude: 21.0915,
    longitude: 71.7630,
    health_score: 91,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Pitch control calibration scheduled on quarterly cycle.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-004',
    name: 'Dwarka Offshore Wind Turbine 4',
    type: 'Wind',
    latitude: 22.2442,
    longitude: 68.9685,
    health_score: 94,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Main gearbox lubrication level adequate. Vibration within IEEE limits.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-005',
    name: 'Porbandar Marine Wind Unit 5',
    type: 'Wind',
    latitude: 21.6420,
    longitude: 69.6010,
    health_score: 88,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Yaw gear drive test passed. Generator stator temperature steady at 62°C.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-006',
    name: 'Jafrabad Coastal Wind Turbine 6',
    type: 'Wind',
    latitude: 20.8710,
    longitude: 71.3640,
    health_score: 96,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Blade harmonic dampeners nominal. Transformer insulation optimal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-007',
    name: 'Jamnagar Wind Array Alpha 7',
    type: 'Wind',
    latitude: 22.4707,
    longitude: 70.0577,
    health_score: 89,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Inverter grid synchronizer verified. Peak power efficiency 98.4%.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-008',
    name: 'Rajkot Wind Energy Station 8',
    type: 'Wind',
    latitude: 22.3039,
    longitude: 70.8022,
    health_score: 93,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Hydraulic disc brake pressure at 185 bar. Systems optimal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-009',
    name: 'Mundra Port Wind Generator 9',
    type: 'Wind',
    latitude: 22.8385,
    longitude: 69.7042,
    health_score: 91,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Nacelle ultrasonic anemometer calibrated with SCADA substation.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'TURBINE-010',
    name: 'Mandvi Beach Wind Turbine 10',
    type: 'Wind',
    latitude: 22.8320,
    longitude: 69.3550,
    health_score: 97,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Tower structural resonance nominal under high Arabian Sea gusts.',
    updated_at: new Date().toISOString(),
  },

  // 10 Gujarat Solar Installations (Charanka, Dholera, Khavda, Radhanpur, Surat, Bhavnagar)
  {
    id: 'SOLAR-001',
    name: 'Charanka Solar Park Phase 1',
    type: 'Solar',
    latitude: 23.9042,
    longitude: 71.2025,
    health_score: 97,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Central inverters operating at 99.1% MPPT efficiency. Dust layer minimal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-002',
    name: 'Charanka Solar Park Phase 2',
    type: 'Solar',
    latitude: 23.9110,
    longitude: 71.2100,
    health_score: 96,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Single-axis tracker tracking solar azimuth with < 0.2° error.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-003',
    name: 'Dholera Ultra Mega Solar Block A',
    type: 'Solar',
    latitude: 22.2470,
    longitude: 72.1930,
    health_score: 94,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Bifacial panel rear-albedo irradiance gain optimal at +12.1%.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-004',
    name: 'Dholera Ultra Mega Solar Block B',
    type: 'Solar',
    latitude: 22.2530,
    longitude: 72.2010,
    health_score: 90,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'DC combiner box string voltages balanced within 0.4%.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-005',
    name: 'Radhanpur Solar Complex Unit 1',
    type: 'Solar',
    latitude: 23.8340,
    longitude: 71.6050,
    health_score: 95,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Thermal UAV drone scan completed. Zero hotspot signatures.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-006',
    name: 'Khavda Hybrid Solar Array S1',
    type: 'Solar',
    latitude: 23.8620,
    longitude: 69.7680,
    health_score: 98,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Automated robotic dry-cleaning cycle completed. Optimal glass reflectance.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-007',
    name: 'Khavda Hybrid Solar Array S2',
    type: 'Solar',
    latitude: 23.8690,
    longitude: 69.7750,
    health_score: 93,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'High-voltage step-up transformer dielectric fluid test normal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-008',
    name: 'Surat Hazira Industrial Solar PV',
    type: 'Solar',
    latitude: 21.1120,
    longitude: 72.6580,
    health_score: 92,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Anti-reflective coating clean. String level current monitoring nominal.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-009',
    name: 'Bhavnagar Coastal Solar Station',
    type: 'Solar',
    latitude: 21.7645,
    longitude: 72.1519,
    health_score: 96,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Substation grounding resistance measured at 1.7 ohms. Well within CEIG spec.',
    updated_at: new Date().toISOString(),
  },
  {
    id: 'SOLAR-010',
    name: 'Surendranagar Solar Farm Alpha',
    type: 'Solar',
    latitude: 22.7280,
    longitude: 71.6370,
    health_score: 94,
    status: 'HEALTHY',
    est_daily_loss: 0,
    recommended_action: 'Grid tie synchronized at 50.02 Hz. Active power factor 0.99.',
    updated_at: new Date().toISOString(),
  }
];

// Helper to generate 24 historical telemetry points leading up to now
export function generateInitialTelemetry(assetId: string, isWind: boolean): TelemetryLog[] {
  const points: TelemetryLog[] = [];
  const now = Date.now();
  const oneHour = 3600 * 1000;

  for (let i = 23; i >= 0; i--) {
    const timestamp = new Date(now - i * oneHour).toISOString();
    
    // Variance modeled on Gujarat ambient & mechanical conditions
    const baseTemp = isWind ? 58 + Math.sin(i / 3) * 4 : 44 + Math.sin(i / 2) * 5;
    const baseVib = isWind ? 1.3 + Math.cos(i / 2) * 0.25 : 0.11 + Math.random() * 0.04;
    const baseVoltage = 685 + Math.sin(i) * 6;
    const baseCurrent = isWind ? 1220 + Math.cos(i) * 50 : 810 + Math.sin(i) * 60;
    const baseSoiling = isWind ? 0 : 3.8 + (23 - i) * 0.12;
    const basePower = isWind ? 2.3 + Math.sin(i / 2) * 0.4 : 1.8 + Math.sin(i / 3) * 0.35;

    points.push({
      id: `${assetId}-hist-${23 - i}`,
      asset_id: assetId,
      temperature: Number(baseTemp.toFixed(1)),
      vibration: Number(baseVib.toFixed(2)),
      voltage: Number(baseVoltage.toFixed(1)),
      current_amps: Number(baseCurrent.toFixed(1)),
      soiling_index: Number(baseSoiling.toFixed(1)),
      power_output_mw: Number(basePower.toFixed(2)),
      timestamp
    });
  }

  return points;
}
